import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";

const worksans = Work_Sans({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    template: "%s | Lendsqr",
    default: "Lendsqr | Home",
  },
  description: "Generated by create next app",

  keywords: ["Lendsqr"],
  // openGraph: {
  //   images: "/opengraph-image.png",
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={worksans.className}>{children}</body>
    </html>
  );
}
